default_agent: main_agent
agents:
  main_agent:
    name: main_agent
    language: python
    node_version: '20'
    entrypoint: C:/Users/d1314219/OneDrive - NCS PTE LTD/dev_vscode/deep_agents/aws/agentcore/agents/main_agent/app.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: none
    source_path: C:\Users\d1314219\OneDrive - NCS PTE LTD\dev_vscode\deep_agents\aws\agentcore\agents\main_agent
    aws:
      execution_role: null
      execution_role_auto_create: true
      account: '654479364634'
      region: ap-southeast-1
      ecr_repository: null
      ecr_auto_create: true
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: null
      agent_arn: null
      agent_session_id: null
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: STM_AND_LTM
      memory_id: null
      memory_arn: null
      memory_name: main_agent_memory
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
